services:
  medx-backend-container:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "3006:3006"

    volumes:
      - ./backend:/app #bind mount
      - /app/node_modules #anonymous volume

    env_file:
      - ./backend/.env

  # medx-frontend-container:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile

  #   ports:
  #     - "3009:3009"
    
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  #   volumes:
  #     - ./dashboard:/app
  #     -  /app/node_modules 

  #   # env_file:
  #     # - ./frontend/.env.local

  #   depends_on:
  #     - medx-backend-container